### ISSUE TITLE
Bluciferum errors in 1.3

### ISSUE THREAD

**Issue by TheOldOne822** [Syrchalis/Blueberries#5]
in 1.3 when Bluciferum is administered it throws an error in the console and doesn't treat/remove any of the conditions it is intended to and fails to be removed from "administer Bluciferum" from the list of medical bills causing all Bluciferum available to be 
administered. 

Same issue existed if using the older version that didn't claim support for 1.3.

Interestingly in the newer version the issue can be fixed either by copying the SyrBlueberries.dll form 1.2/Assemblies/ to 1.3/Assemblies/ overriding the version in there or deleting the 1.3 folder thus making 1.3 fall back to loading the from the 1.2 folder.

I would have just left this in the Workshop Comments but I have the GOG version of Rimworld so can't post on the Steam Workshop other than the forums

**Comment by Syrchalis** [comment]
Pretty sure I just messed up the upload.

**Comment by TheOldOne822** [comment]
Yes I closed it because the next version worked without moving around files
